# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build bootcamp with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'    
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build commons  
      run: mvn -B install --file v1.0.0-commons/pom.xml
    - name: Build solution  
      run: mvn -B package --file v1.0.0-solution/pom.xml
    - name: Build demo  
      run: mvn -B package --file v0.1.0-demo/pom.xml
    - name: Build lab  
      run: mvn -B package --file v0.2.0-lab/pom.xml
